name: CustomPortals
version: 1.0
author: jacob5257
main: com.jacob5257.CustomPortals.CustomPortals
api-version: 1.20

permissions:
   customportals.create:
      description: Allows you to create portals to custom worlds.
      default: op